set mouse=a
set numberwidth=1
set clipboard=unnamedplus
syntax enable
set showcmd
set ruler
set encoding=utf-8
set sw=4
set noshowmode
set relativenumber
set expandtab
set tabstop=2
set shiftwidth=2
set number
set cmdheight=2
set nowrap
set noswapfile
set nobackup
set termguicolors
set colorcolumn=120
highlight ColoColum ctermbg=0 guibg=LightGray
set cursorline
set hidden
